version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: recetteapp/recette-spring-boot-backend
    container_name: recette-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
